# Global default DEVELOPMENT settings for ALL apps in the solution
Logging:
  LogLevel:
    Default: Debug
    Microsoft: Debug
    Steeltoe.Extensions.Configuration.ConfigServer: Warning

Spring:
  Cloud:
    Config:
      Enabled: false # disable config server in local development
  Boot:
    Admin:
      Client:
        Url: http://localhost:8088
        Metadata:
          "user.name": admin
          "user.password": admin
Management:
  Endpoints:
    Actuator:
      EnableSecurity: false
  Tracing:
    Exporter:
      Zipkin:
        Endpoint: http://localhost:9411

#if enableSecurity
Authentication:
  Bearer:
    Authority: https://login.run.pcfone.io
#endif
Urls: ${ASPNETCORE_URLS?http://localhost:5000;https://localhost:5001}