# Global default DEVELOPMENT settings for ALL apps in the solution
Logging:
  LogLevel:
    Default: Debug
Spring:
  Boot:
    Admin:
      Client:
        Url: http://localhost:8088
        Metadata:
          "User.Name": admin
          "User.Password": admin
Management:
  Endpoints:
    Actuator:
      Exposure:
        Include:
          - "*"
#if enableSecurity
Authentication:
  Bearer:
    Authority: https://login.run.pcfone.io
#endif
Urls: ${ASPNETCORE_URLS}