# Global default DEVELOPMENT settings for ALL apps in the solution
Logging:
  LogLevel:
    Default: Debug
Management:
  Endpoints:
    Actuator:
      Exposure:
        Include:
          - "*"
#if enableSecurity
Authentication:
  Bearer:
    Authority: https://login.run.pcfone.io
#endif