# Global default DEVELOPMENT settings for ALL apps in the solution
Logging:
  LogLevel:
    Default: Debug
Spring:
  Boot:
    Admin:
      Client:
        Url: http://localhost:8088
        Metadata:
          "user.name": admin
          "user.password": admin
Management:
  Tracing:
    Exporter:
      Zipkin:
        Endpoint: http://localhost:9411

#if enableSecurity
Authentication:
  Bearer:
    Authority: https://login.run.pcfone.io
#endif
Urls: ${ASPNETCORE_URLS}