apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dotnet-accelerator 
  name: dotnet-accelerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dotnet-accelerator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotnet-accelerator
        app.kubernetes.io/part-of: dotnet-accelerator
    spec:
      containers:
      - name: app
        image: macsux/dotnet-accelerator:latest
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        imagePullPolicy: Always
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8080
        ports:
        - containerPort: 8080
        - containerPort: 22
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8080